name: qtim_tst
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  go_router: ^14.8.1
  drift: ^2.25.1
  path_provider: ^2.1.5
  json_annotation: ^4.9.0
  drift_flutter: ^0.2.4
  copy_with_extension_gen: ^6.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  riverpod_generator: ^2.6.5
  json_serializable: ^6.9.4
  build_runner: ^2.4.15
  drift_dev: ^2.25.2
  custom_lint: ^0.7.5
  riverpod_lint: ^2.6.5

flutter:
  uses-material-design: true
  assets:
    - assets/user_data.json

